# Generated by Django 6.0.4 on 2026-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDelivery_DB',
            fields=[
                ('Order_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=30)),
                ('OrderDate', models.DateField()),
                ('ItemName', models.CharField(max_length=100)),
                ('OrderQty', models.IntegerField()),
                ('UnitPrice', models.FloatField()),
                ('TotalAmount', models.FloatField()),
                ('DeliveryAddress', models.CharField(max_length=200)),
            ],
        ),
    ]
